name: Docker Build Deploy
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: run shell script
      run: echo commit hash is ${{ github.sha }}
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
   - name: Build payment service docker image
      run: |
        cd ProductService 
        docker build . --file Dockerfile --tag productrepo.azurecr.io/productservice:v1 
    - name: Push cart service docker image
      run: docker push roductrepo.azurecr.io/productservice:v1
      # with:
      #   context: .
      #   file: ./Dockerfile
      #   push: true
      #   tags: productrepo.azurecr.io/productservice:v1
    -name: deploy
     run: apply -f ./k8s